let
    Source = Pdf.Tables(File.Contents("C:\Users\phakk\Desktop\9EXPERT-Case Study Power BI Desktop-Version 30\Datasources\Clients.pdf"), [Implementation="1.3"]),
    Page1 = Source{[Id="Page001"]}[Data],
    #"Removed Top Rows" = Table.Skip(Page1,1),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Address2", "County", "Column7", "Column8", "Column11", "WebSite", "Address1", "PostCode", "ClientSince"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns",null,"Medium",Replacer.ReplaceValue,{"ClientSize"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"ClientID", Int64.Type}, {"ClientName", type text}, {"Town", type text}, {"CountryID", Int64.Type}, {"ClientType", type text}, {"ClientSize", type text}, {"IsCreditWorthy", Int64.Type}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"IsCreditWorthy", type logical}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"CountryID"}, Countries, {"CountryID"}, "Countries", JoinKind.LeftOuter),
    #"Expanded Countries" = Table.ExpandTableColumn(#"Merged Queries", "Countries", {"CountryName", "CountryFlagURL", "Continent"}, {"CountryName", "CountryFlagURL", "Continent"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Countries",{"CountryID"})
in
    #"Removed Columns1"
