let
    Source = Excel.Workbook(File.Contents("C:\Users\phakk\Desktop\9EXPERT-Case Study Power BI Desktop-Version 30\Datasources\SalesData.xlsx"), null, true),
    Sales2021_2022_Sheet = Source{[Item="Sales2021_2022",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sales2021_2022_Sheet, [PromoteAllScalars=true]),
    #"Appended Query" = Table.Combine({#"Promoted Headers", Sales2023}),
    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Appended Query", {{"InvoiceDate", type date}, {"Registration_Date", type date}}, "en-GB"),
    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"TotalDiscount", type number}, {"DeliveryCharge", type number}, {"SalePrice", type number}, {"Make", type text}, {"Marque", type text}, {"CostPrice", type number}, {"ColourID", Int64.Type}, {"ClientID", Int64.Type}, {"LabourCost", type number}, {"SpareParts", Int64.Type}, {"MileageRange", type text}, {"MileageRangeSort", Int64.Type}, {"VehicleType", type text}, {"InvoiceNumber", Int64.Type}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Make", "Marque", "VehicleType"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Make", "Marque"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "VehicleKey"}}),
    #"Inserted Merged Column" = Table.AddColumn(#"Renamed Columns", "VehicleName", each Text.Combine({[Make], " ", [Marque]}), type text)
in
    #"Inserted Merged Column"
